# Generated by Django 5.2.11 on 2026-02-11 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='Unique OPIS Truckstop ID', unique=True)),
                ('name', models.CharField(help_text='Station name', max_length=200)),
                ('address', models.CharField(blank=True, help_text='Street address', max_length=300)),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='State code (e.g., CA, NY)', max_length=2)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=3, help_text='Retail fuel price per gallon (USD)', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Longitude coordinate', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='lat_lon_idx'), models.Index(fields=['retail_price'], name='price_idx'), models.Index(fields=['state', 'city'], name='location_idx')],
            },
        ),
    ]
